version: '3.9'
services:
  db:
    image: postgres:14
    env_file:
      - ${ENV_FILE:-.env.dev} # Default to .env.dev
    expose:
      - '5432'
    volumes:
      - group-project:/var/lib/postgresql/data
      - ./src/init_data:/docker-entrypoint-initdb.d

  web:
    image: node:lts
    working_dir: /repository
    env_file:
      - ${ENV_FILE:-.env.dev} # Default to .env.dev
    environment:
      - NODE_ENV=${NODE_ENV:-development} # Default to development
    depends_on:
      - db
    ports:
      - '3000:3000'
    volumes:
      - ./:/repository
      - ./src/resources/img:/repository/src/resources/img
    command: 'npm run testandrun'

volumes:
  group-project: