insert into users (username, first_name, last_name, password_hash, email) values ('rdobbyn0', 'Richart', 'Dobbyn', '$2a$04$bVhGxx39Cjy0dMS69ePnDuVXDZAF3qJTaWjCEuO0j6yTgQB.j4RIe', 'rdobbyn0@springer.com');
insert into users (username, first_name, last_name, password_hash, email) values ('cyashunin1', 'Charita', 'Yashunin', '$2a$04$rY2vaAk4LWcJnLP4BMrQmurKCGKtyLTaffA23gZj2fAQkwtXzF/QK', 'cyashunin1@jugem.jp');
insert into users (username, first_name, last_name, password_hash, email) values ('gnotman2', 'Garret', 'Notman', '$2a$04$jgWq704.Yiucq46BcHnCXurddb9LrGRc8TaV24McqgC1vurNUZdhe', 'gnotman2@telegraph.co.uk');
insert into users (username, first_name, last_name, password_hash, email) values ('cboule3', 'Camila', 'Boule', '$2a$04$vv7b.dRK3vCVI9uLWF/m/OaVZ/y48fmp9pM/flpzQGcHIlkixr3cq', 'cboule3@netvibes.com');
insert into users (username, first_name, last_name, password_hash, email) values ('nashwood4', 'Natassia', 'Ashwood', '$2a$04$VJFiAMbTvAs30Zp7us/rX.juGw//Nax3JxUGFu3SXGrVQVAO9Nada', 'nashwood4@dot.gov');
insert into users (username, first_name, last_name, password_hash, email) values ('nmacandreis5', 'Noland', 'MacAndreis', '$2a$04$09ZHDdqIobo6ll5jxr996.AkjwLXotPrsc4IGmC2utQzwp.sV9ph.', 'nmacandreis5@trellian.com');
insert into users (username, first_name, last_name, password_hash, email) values ('toshaughnessy6', 'Torie', 'O''Shaughnessy', '$2a$04$73hVljhzM2uDWHGaY2g5ZeuNzBK8V8qFpoycGuLdTVmeAoSxI/Pyi', 'toshaughnessy6@wordpress.org');
insert into users (username, first_name, last_name, password_hash, email) values ('nchiverstone7', 'Nettle', 'Chiverstone', '$2a$04$FUy3DGT0kf5XrW2cTpNP0.Gd56TQor8dKFu/cyqfA.cMtl3nBi41u', 'nchiverstone7@biblegateway.com');
insert into users (username, first_name, last_name, password_hash, email) values ('sfoker8', 'Shari', 'Foker', '$2a$04$9UVADLwdVZiqpc9xFUuYT.hlvkuC25ui81I6E7ub1S35k2stcCrAa', 'sfoker8@hugedomains.com');
insert into users (username, first_name, last_name, password_hash, email) values ('cknevit9', 'Clement', 'Knevit', '$2a$04$9kACQ0SRu0F3wl3CR896aerc2umPVuQV5bGm76hW6GBbkIg90CNIC', 'cknevit9@eepurl.com');
insert into users (username, first_name, last_name, password_hash, email) values ('kfostersmitha', 'Kurtis', 'Foster-Smith', '$2a$04$BKIrQf/4FnLpBF3UxfT1QeRXbUISmGhZmGCByUarpvifBp9qW8cm.', 'kfostersmitha@cafepress.com');
insert into users (username, first_name, last_name, password_hash, email) values ('tmckibbinb', 'Ty', 'McKibbin', '$2a$04$d0G.xBLtpAhyYOzJtGR5we08TKWnkFgGhsioro2vri2qhOwVGHQcW', 'tmckibbinb@ycombinator.com');
insert into users (username, first_name, last_name, password_hash, email) values ('tdoutchc', 'Tory', 'Doutch', '$2a$04$L8NSWGHCcQmoalPXHj8OLeYWfXQ.0wqB2q.gux36PE7GgenNfN61e', 'tdoutchc@hud.gov');
insert into users (username, first_name, last_name, password_hash, email) values ('jsuttled', 'Jewell', 'Suttle', '$2a$04$AUH5A3K75dyMr6CzVZzjT.kbY9t69j8kAlT3BCkv3usStqssupogi', 'jsuttled@rambler.ru');
insert into users (username, first_name, last_name, password_hash, email) values ('ucrippene', 'Ursola', 'Crippen', '$2a$04$XTI0SgiYCE5hhtX5ZI6s5.aZT/unHB1qUP/ABuvg6uYBMVzkojalG', 'ucrippene@china.com.cn');
insert into users (username, first_name, last_name, password_hash, email) values ('bdonaldsonf', 'Beret', 'Donaldson', '$2a$04$EoxfzR.z3HQokzOlys8U/uPTtxiNXGIJ3BDkRwgFIz0P96qlVRQoW', 'bdonaldsonf@fc2.com');
insert into users (username, first_name, last_name, password_hash, email) values ('fabbieg', 'Freddie', 'Abbie', '$2a$04$aR1Kx0k9AdeGD5j0dCwkPuTcVo1GbdRgAAkSn5rxa6arce/yopKYi', 'fabbieg@reddit.com');
insert into users (username, first_name, last_name, password_hash, email) values ('mduerh', 'Mycah', 'Duer', '$2a$04$Y6qL4AKGuOZcYuql2btw6eq04kbt8OXtizXWsluwsvIeYAptrNGPm', 'mduerh@tamu.edu');
insert into users (username, first_name, last_name, password_hash, email) values ('egipsoni', 'Eveleen', 'Gipson', '$2a$04$2kdcwop9gnKVMcaEmknMzulUU1s9FPnFRs3Y9MqSFebE4FTfIhduW', 'egipsoni@epa.gov');
insert into users (username, first_name, last_name, password_hash, email) values ('epionterj', 'Emera', 'Pionter', '$2a$04$Aeej/xHGxB4sftXfYj9QKu5ryvzl0nenI2LQ5o7V.jlUte2AJjvGy', 'epionterj@ca.gov');
insert into users (username, first_name, last_name, password_hash, email) values ('mhanabyk', 'Merle', 'Hanaby', '$2a$04$LLhSDs6OfVrqHsC2lk7ECuJQKCcNwq1ch5h6FX/mxigjMdJWIcDdi', 'mhanabyk@upenn.edu');
insert into users (username, first_name, last_name, password_hash, email) values ('gdonohuel', 'Ginger', 'Donohue', '$2a$04$xc1CwvEwJd3Sy1TR60kvb.VgNI3HkyTb7uRvMuQXV6xJ.KQSaiIsC', 'gdonohuel@xing.com');
insert into users (username, first_name, last_name, password_hash, email) values ('hbynethm', 'Hersh', 'Byneth', '$2a$04$631KPtzOqGxtVrEb//CgRujWfVRF2yJxpANZTaE3qzOZE9ZKB2QPa', 'hbynethm@intel.com');
insert into users (username, first_name, last_name, password_hash, email) values ('jhaggartyn', 'Jaquelyn', 'Haggarty', '$2a$04$LypZZilv7DZSrBFcBoudXurhTgN2CP3HAG.uEjfEmX3qlDTNaNFVi', 'jhaggartyn@sakura.ne.jp');
insert into users (username, first_name, last_name, password_hash, email) values ('cblinkhorno', 'Chucho', 'Blinkhorn', '$2a$04$MeL4WF05SSoRHLnVELwI1uRB0kSYX43yREHMnbAvhe6vLoaJ./GzS', 'cblinkhorno@sohu.com');

insert into pets (name, class, breed, age, color, weight, birthday, eye_color, location, bio, image_url) values ('Toiboid Legh', 'Ocelot', 'Ragdoll', 11.4, 'Green', 1.5, '6/6/2007', 'Aquamarine', 'Belyye Stolby', '-', '-');
insert into pets (name, class, breed, age, color, weight, birthday, eye_color, location, bio, image_url) values ('Daffie Blissitt', 'Weaver, red-billed buffalo', 'Golden Retriever', 5.9, 'Fuscia', 178.3, '4/26/2003', 'Teal', 'Cangkreng', '-', '-');
insert into pets (name, class, breed, age, color, weight, birthday, eye_color, location, bio, image_url) values ('Rriocard Guilloux', 'Chilean flamingo', 'Labrador Retriever', 15.6, 'Purple', 147.7, '7/26/2013', 'Red', 'Adiaké', '-', '-');
insert into pets (name, class, breed, age, color, weight, birthday, eye_color, location, bio, image_url) values ('Cariotta Leonard', 'Sheep, stone', 'German Shepherd', 5.9, 'Orange', 104.8, '10/20/2013', 'Teal', 'Petrivka', '-', '-');
insert into pets (name, class, breed, age, color, weight, birthday, eye_color, location, bio, image_url) values ('Chickie Dinneen', 'Southern boubou', 'Labrador Retriever', 1.2, 'Red', 18.0, '3/31/2007', 'Yellow', 'Alíartos', '-', '-');
insert into pets (name, class, breed, age, color, weight, birthday, eye_color, location, bio, image_url) values ('Maurie Somerville', 'Hyena, striped', 'Ragdoll', 15.6, 'Khaki', 191.4, '6/13/2007', 'Crimson', 'Kalān Deh', '-', '-');
insert into pets (name, class, breed, age, color, weight, birthday, eye_color, location, bio, image_url) values ('Oralia Spencelayh', 'Possum, pygmy', 'Bengal', 3.9, 'Maroon', 131.7, '11/15/2015', 'Aquamarine', 'Hongqi', '-', '-');
insert into pets (name, class, breed, age, color, weight, birthday, eye_color, location, bio, image_url) values ('Sharlene Denacamp', 'Hanuman langur', 'Ragdoll', 19.2, 'Mauv', 160.6, '9/6/2007', 'Indigo', 'Daogao', '-', '-');
insert into pets (name, class, breed, age, color, weight, birthday, eye_color, location, bio, image_url) values ('Susanna Costy', 'Grouse, sage', 'Labrador Retriever', 7.4, 'Mauv', 91.3, '9/3/2006', 'Indigo', 'Los Pinos', '-', '-');
insert into pets (name, class, breed, age, color, weight, birthday, eye_color, location, bio, image_url) values ('Frasquito Dust', 'Sheep, red', 'German Shepherd', 8.7, 'Red', 120.0, '10/15/2020', 'Orange', 'Nal’chik', '-', '-');
insert into pets (name, class, breed, age, color, weight, birthday, eye_color, location, bio, image_url) values ('Aimee Glynn', 'Deer, swamp', 'Ragdoll', 11.5, 'Aquamarine', 59.9, '8/5/2006', 'Yellow', 'Fubin', '-', '-');
insert into pets (name, class, breed, age, color, weight, birthday, eye_color, location, bio, image_url) values ('Elisa Cotterell', 'Dusky gull', 'Persian', 12.1, 'Fuscia', 117.1, '12/30/2008', 'Turquoise', 'Dalonghua', '-', '-');
insert into pets (name, class, breed, age, color, weight, birthday, eye_color, location, bio, image_url) values ('Walton Martyntsev', 'Woolly-necked stork', 'Bengal', 18.8, 'Crimson', 68.2, '4/21/2019', 'Puce', 'Glubokiy', '-', '-');
insert into pets (name, class, breed, age, color, weight, birthday, eye_color, location, bio, image_url) values ('Blondy Danielkiewicz', 'Francolin, coqui', 'Siamese', 9.2, 'Crimson', 64.4, '1/23/2000', 'Violet', 'Lukavice', '-', '-');
insert into pets (name, class, breed, age, color, weight, birthday, eye_color, location, bio, image_url) values ('Alessandra Yanukhin', 'Blue peacock', 'Golden Retriever', 5.0, 'Crimson', 38.8, '9/4/2009', 'Crimson', 'Damanhūr', '-', '-');
insert into pets (name, class, breed, age, color, weight, birthday, eye_color, location, bio, image_url) values ('Darryl Robrow', 'Brindled gnu', 'Golden Retriever', 18.0, 'Indigo', 13.5, '1/14/2019', 'Indigo', 'Novomichurinsk', '-', '-');
insert into pets (name, class, breed, age, color, weight, birthday, eye_color, location, bio, image_url) values ('Finley Stonehewer', 'Seal, harbor', 'German Shepherd', 16.4, 'Indigo', 153.6, '4/12/2013', 'Goldenrod', 'Kertasari', '-', '-');
insert into pets (name, class, breed, age, color, weight, birthday, eye_color, location, bio, image_url) values ('Gianna Cone', 'Eastern cottontail rabbit', 'Persian', 10.0, 'Orange', 4.7, '10/28/2009', 'Puce', 'Huayan', '-', '-');
insert into pets (name, class, breed, age, color, weight, birthday, eye_color, location, bio, image_url) values ('Eben Trunby', 'Painted stork', 'Golden Retriever', 18.6, 'Purple', 92.5, '9/11/2012', 'Teal', 'Piława Górna', '-', '-');
insert into pets (name, class, breed, age, color, weight, birthday, eye_color, location, bio, image_url) values ('Javier Audenis', 'Frogmouth, tawny', 'Beagle', 2.6, 'Green', 43.7, '1/2/2002', 'Maroon', 'Kristinestad', '-', '-');
insert into pets (name, class, breed, age, color, weight, birthday, eye_color, location, bio, image_url) values ('Larine Courtier', 'Hudsonian godwit', 'Golden Retriever', 15.5, 'Violet', 39.2, '12/16/2013', 'Teal', 'Dodola', '-', '-');
insert into pets (name, class, breed, age, color, weight, birthday, eye_color, location, bio, image_url) values ('Vaughn Huyhton', 'Starfish, crown of thorns', 'Labrador Retriever', 15.2, 'Orange', 11.0, '1/26/2008', 'Yellow', 'Ajdabiya', '-', '-');
insert into pets (name, class, breed, age, color, weight, birthday, eye_color, location, bio, image_url) values ('Law Pensom', 'Fox, silver-backed', 'Golden Retriever', 19.8, 'Yellow', 129.4, '1/24/2009', 'Purple', 'Málaga', '-', '-');
insert into pets (name, class, breed, age, color, weight, birthday, eye_color, location, bio, image_url) values ('Annice Sichardt', 'Weaver, red-billed buffalo', 'Ragdoll', 11.3, 'Goldenrod', 120.5, '1/9/2010', 'Red', 'Viljoenskroon', '-', '-');
insert into pets (name, class, breed, age, color, weight, birthday, eye_color, location, bio, image_url) values ('Bern Valente', 'Snowy owl', 'Beagle', 14.6, 'Aquamarine', 162.4, '1/4/2005', 'Crimson', 'Monastyrshchina', '-', '-');

insert into users_to_pets (user_id, pet_id) values (1, 1);
insert into users_to_pets (user_id, pet_id) values (2, 2);
insert into users_to_pets (user_id, pet_id) values (3, 3);
insert into users_to_pets (user_id, pet_id) values (4, 4);
insert into users_to_pets (user_id, pet_id) values (5, 5);
insert into users_to_pets (user_id, pet_id) values (6, 6);
insert into users_to_pets (user_id, pet_id) values (7, 7);
insert into users_to_pets (user_id, pet_id) values (8, 8);
insert into users_to_pets (user_id, pet_id) values (9, 9);
insert into users_to_pets (user_id, pet_id) values (10, 10);
insert into users_to_pets (user_id, pet_id) values (11, 11);
insert into users_to_pets (user_id, pet_id) values (12, 12);
insert into users_to_pets (user_id, pet_id) values (13, 13);
insert into users_to_pets (user_id, pet_id) values (14, 14);
insert into users_to_pets (user_id, pet_id) values (15, 15);
insert into users_to_pets (user_id, pet_id) values (16, 16);
insert into users_to_pets (user_id, pet_id) values (17, 17);
insert into users_to_pets (user_id, pet_id) values (18, 18);
insert into users_to_pets (user_id, pet_id) values (19, 19);
insert into users_to_pets (user_id, pet_id) values (20, 20);
insert into users_to_pets (user_id, pet_id) values (21, 21);
insert into users_to_pets (user_id, pet_id) values (22, 22);
insert into users_to_pets (user_id, pet_id) values (23, 23);
insert into users_to_pets (user_id, pet_id) values (24, 24);
insert into users_to_pets (user_id, pet_id) values (25, 25);


