insert into users (username, first_name, last_name, password_hash, email) values ('rdobbyn0', 'Richart', 'Dobbyn', '$2a$04$bVhGxx39Cjy0dMS69ePnDuVXDZAF3qJTaWjCEuO0j6yTgQB.j4RIe', 'rdobbyn0@springer.com');
insert into users (username, first_name, last_name, password_hash, email) values ('cyashunin1', 'Charita', 'Yashunin', '$2a$04$rY2vaAk4LWcJnLP4BMrQmurKCGKtyLTaffA23gZj2fAQkwtXzF/QK', 'cyashunin1@jugem.jp');
insert into users (username, first_name, last_name, password_hash, email) values ('gnotman2', 'Garret', 'Notman', '$2a$04$jgWq704.Yiucq46BcHnCXurddb9LrGRc8TaV24McqgC1vurNUZdhe', 'gnotman2@telegraph.co.uk');
insert into users (username, first_name, last_name, password_hash, email) values ('cboule3', 'Camila', 'Boule', '$2a$04$vv7b.dRK3vCVI9uLWF/m/OaVZ/y48fmp9pM/flpzQGcHIlkixr3cq', 'cboule3@netvibes.com');
insert into users (username, first_name, last_name, password_hash, email) values ('nashwood4', 'Natassia', 'Ashwood', '$2a$04$VJFiAMbTvAs30Zp7us/rX.juGw//Nax3JxUGFu3SXGrVQVAO9Nada', 'nashwood4@dot.gov');
insert into users (username, first_name, last_name, password_hash, email) values ('nmacandreis5', 'Noland', 'MacAndreis', '$2a$04$09ZHDdqIobo6ll5jxr996.AkjwLXotPrsc4IGmC2utQzwp.sV9ph.', 'nmacandreis5@trellian.com');
insert into users (username, first_name, last_name, password_hash, email) values ('toshaughnessy6', 'Torie', 'O''Shaughnessy', '$2a$04$73hVljhzM2uDWHGaY2g5ZeuNzBK8V8qFpoycGuLdTVmeAoSxI/Pyi', 'toshaughnessy6@wordpress.org');
insert into users (username, first_name, last_name, password_hash, email) values ('nchiverstone7', 'Nettle', 'Chiverstone', '$2a$04$FUy3DGT0kf5XrW2cTpNP0.Gd56TQor8dKFu/cyqfA.cMtl3nBi41u', 'nchiverstone7@biblegateway.com');
insert into users (username, first_name, last_name, password_hash, email) values ('sfoker8', 'Shari', 'Foker', '$2a$04$9UVADLwdVZiqpc9xFUuYT.hlvkuC25ui81I6E7ub1S35k2stcCrAa', 'sfoker8@hugedomains.com');
insert into users (username, first_name, last_name, password_hash, email) values ('cknevit9', 'Clement', 'Knevit', '$2a$04$9kACQ0SRu0F3wl3CR896aerc2umPVuQV5bGm76hW6GBbkIg90CNIC', 'cknevit9@eepurl.com');
insert into users (username, first_name, last_name, password_hash, email) values ('kfostersmitha', 'Kurtis', 'Foster-Smith', '$2a$04$BKIrQf/4FnLpBF3UxfT1QeRXbUISmGhZmGCByUarpvifBp9qW8cm.', 'kfostersmitha@cafepress.com');
insert into users (username, first_name, last_name, password_hash, email) values ('tmckibbinb', 'Ty', 'McKibbin', '$2a$04$d0G.xBLtpAhyYOzJtGR5we08TKWnkFgGhsioro2vri2qhOwVGHQcW', 'tmckibbinb@ycombinator.com');
insert into users (username, first_name, last_name, password_hash, email) values ('tdoutchc', 'Tory', 'Doutch', '$2a$04$L8NSWGHCcQmoalPXHj8OLeYWfXQ.0wqB2q.gux36PE7GgenNfN61e', 'tdoutchc@hud.gov');
insert into users (username, first_name, last_name, password_hash, email) values ('jsuttled', 'Jewell', 'Suttle', '$2a$04$AUH5A3K75dyMr6CzVZzjT.kbY9t69j8kAlT3BCkv3usStqssupogi', 'jsuttled@rambler.ru');
insert into users (username, first_name, last_name, password_hash, email) values ('ucrippene', 'Ursola', 'Crippen', '$2a$04$XTI0SgiYCE5hhtX5ZI6s5.aZT/unHB1qUP/ABuvg6uYBMVzkojalG', 'ucrippene@china.com.cn');
insert into users (username, first_name, last_name, password_hash, email) values ('bdonaldsonf', 'Beret', 'Donaldson', '$2a$04$EoxfzR.z3HQokzOlys8U/uPTtxiNXGIJ3BDkRwgFIz0P96qlVRQoW', 'bdonaldsonf@fc2.com');
insert into users (username, first_name, last_name, password_hash, email) values ('fabbieg', 'Freddie', 'Abbie', '$2a$04$aR1Kx0k9AdeGD5j0dCwkPuTcVo1GbdRgAAkSn5rxa6arce/yopKYi', 'fabbieg@reddit.com');
insert into users (username, first_name, last_name, password_hash, email) values ('mduerh', 'Mycah', 'Duer', '$2a$04$Y6qL4AKGuOZcYuql2btw6eq04kbt8OXtizXWsluwsvIeYAptrNGPm', 'mduerh@tamu.edu');
insert into users (username, first_name, last_name, password_hash, email) values ('egipsoni', 'Eveleen', 'Gipson', '$2a$04$2kdcwop9gnKVMcaEmknMzulUU1s9FPnFRs3Y9MqSFebE4FTfIhduW', 'egipsoni@epa.gov');
insert into users (username, first_name, last_name, password_hash, email) values ('epionterj', 'Emera', 'Pionter', '$2a$04$Aeej/xHGxB4sftXfYj9QKu5ryvzl0nenI2LQ5o7V.jlUte2AJjvGy', 'epionterj@ca.gov');
insert into users (username, first_name, last_name, password_hash, email) values ('mhanabyk', 'Merle', 'Hanaby', '$2a$04$LLhSDs6OfVrqHsC2lk7ECuJQKCcNwq1ch5h6FX/mxigjMdJWIcDdi', 'mhanabyk@upenn.edu');
insert into users (username, first_name, last_name, password_hash, email) values ('gdonohuel', 'Ginger', 'Donohue', '$2a$04$xc1CwvEwJd3Sy1TR60kvb.VgNI3HkyTb7uRvMuQXV6xJ.KQSaiIsC', 'gdonohuel@xing.com');
insert into users (username, first_name, last_name, password_hash, email) values ('hbynethm', 'Hersh', 'Byneth', '$2a$04$631KPtzOqGxtVrEb//CgRujWfVRF2yJxpANZTaE3qzOZE9ZKB2QPa', 'hbynethm@intel.com');
insert into users (username, first_name, last_name, password_hash, email) values ('jhaggartyn', 'Jaquelyn', 'Haggarty', '$2a$04$LypZZilv7DZSrBFcBoudXurhTgN2CP3HAG.uEjfEmX3qlDTNaNFVi', 'jhaggartyn@sakura.ne.jp');
insert into users (username, first_name, last_name, password_hash, email) values ('cblinkhorno', 'Chucho', 'Blinkhorn', '$2a$04$MeL4WF05SSoRHLnVELwI1uRB0kSYX43yREHMnbAvhe6vLoaJ./GzS', 'cblinkhorno@sohu.com');

insert into pets (name, class, breed, age, color, weight, birthday, eye_color, location, bio, price, image_url) values ('Eziechiele Harcase', 'cat', 'British Shorthair', 8.7, 'Crimson', 106.9, '9/8/2005', 'Turquoise', '039 Algoma Drive', 'incubate interactive mindshare', 3670.49, 'IMG_8981.jpg');
insert into pets (name, class, breed, age, color, weight, birthday, eye_color, location, bio, price, image_url) values ('Rodge Joselin', 'cat', 'Russian Blue', 10.8, 'Fuscia', 21.1, '7/9/2012', 'Crimson', '91 Rusk Trail', 'benchmark world-class niches', 4910.63, 'IMG_8981.jpg');
insert into pets (name, class, breed, age, color, weight, birthday, eye_color, location, bio, price, image_url) values ('Jim Flea', 'dog', 'Labrador Retriever', 15.2, 'Red', 154.9, '5/10/2011', 'Yellow', '39 Forest Run Place', 'incubate synergistic partnerships', 2314.87, 'IMG_8981.jpg');
insert into pets (name, class, breed, age, color, weight, birthday, eye_color, location, bio, price, image_url) values ('Curtice Breawood', 'dog', 'Siberian Husky', 15.5, 'Green', 74.7, '1/7/2014', 'Goldenrod', '1957 Hauk Pass', 'unleash rich e-commerce', 4665.23, 'IMG_8981.jpg');
insert into pets (name, class, breed, age, color, weight, birthday, eye_color, location, bio, price, image_url) values ('Lorianne Paddefield', 'cat', 'American Shorthair', 5.8, 'Puce', 5.9, '4/3/2003', 'Khaki', '867 Pond Way', 'transition end-to-end communities', 1842.92, 'IMG_8981.jpg');
insert into pets (name, class, breed, age, color, weight, birthday, eye_color, location, bio, price, image_url) values ('Rees Kondratowicz', 'dog', 'Golden Retriever', 0.7, 'Violet', 145.0, '9/1/2020', 'Teal', '039 Hoard Center', 'reintermediate wireless partnerships', 1178.30, 'IMG_8981.jpg');
insert into pets (name, class, breed, age, color, weight, birthday, eye_color, location, bio, price, image_url) values ('Collie O''Corrigane', 'dog', 'Labrador Retriever', 4.1, 'Green', 93.6, '11/4/2012', 'Green', '3825 Sloan Street', 'revolutionize sexy synergies', 2302.72, 'IMG_8981.jpg');
insert into pets (name, class, breed, age, color, weight, birthday, eye_color, location, bio, price, image_url) values ('Steward Osgordby', 'cat', 'British Shorthair', 5.0, 'Red', 105.8, '12/31/2011', 'Red', '2 Mendota Avenue', 'embrace granular infrastructures', 0, 'IMG_8981.jpg');
insert into pets (name, class, breed, age, color, weight, birthday, eye_color, location, bio, price, image_url) values ('Othello Greave', 'dog', 'Siberian Husky', 14.0, 'Khaki', 162.5, '11/11/2015', 'Crimson', '60909 Roxbury Crossing', 'innovate web-enabled users', 2498.23, 'IMG_8981.jpg');
insert into pets (name, class, breed, age, color, weight, birthday, eye_color, location, bio, price, image_url) values ('Marcela Lambot', 'dog', 'German Shepherd', 17.0, 'Crimson', 106.4, '1/28/2002', 'Puce', '3147 Sheridan Plaza', 'cultivate extensible eyeballs', 2105.44, 'IMG_8981.jpg');
insert into pets (name, class, breed, age, color, weight, birthday, eye_color, location, bio, price, image_url) values ('Midge Daviddi', 'dog', 'Golden Retriever', 0.6, 'Puce', 112.6, '7/7/2003', 'Turquoise', '43 Village Green Lane', 'harness value-added technologies', 4288.20, 'IMG_8981.jpg');
insert into pets (name, class, breed, age, color, weight, birthday, eye_color, location, bio, price, image_url) values ('Mile Hindmore', 'cat', 'Russian Blue', 14.6, 'Teal', 107.1, '9/22/2002', 'Puce', '52 Fremont Terrace', 'redefine cutting-edge systems', 1373.83, 'IMG_8981.jpg');
insert into pets (name, class, breed, age, color, weight, birthday, eye_color, location, bio, price, image_url) values ('Myles Rutland', 'cat', 'American Shorthair', 19.3, 'Khaki', 45.4, '5/10/2005', 'Puce', '8045 Merchant Way', 'engineer ubiquitous web services', 1040.02, 'IMG_8981.jpg');
insert into pets (name, class, breed, age, color, weight, birthday, eye_color, location, bio, price, image_url) values ('Brendon Brammar', 'dog', 'German Shepherd', 14.2, 'Aquamarine', 133.5, '12/27/2007', 'Crimson', '14 Canary Point', 'scale value-added experiences', 3897.42, 'IMG_8981.jpg');
insert into pets (name, class, breed, age, color, weight, birthday, eye_color, location, bio, price, image_url) values ('Charlot McCleod', 'dog', 'Labrador Retriever', 10.0, 'Purple', 42.4, '12/15/2009', 'Blue', '755 Florence Road', 'optimize sticky schemas', 3979.91, 'IMG_8981.jpg');
insert into pets (name, class, breed, age, color, weight, birthday, eye_color, location, bio, price, image_url) values ('Ailsun Dongate', 'dog', 'Siberian Husky', 10.8, 'Orange', 197.4, '5/8/2003', 'Violet', '2 Pankratz Junction', 'matrix B2B platforms', 2080.93, 'IMG_8981.jpg');
insert into pets (name, class, breed, age, color, weight, birthday, eye_color, location, bio, price, image_url) values ('Hasheem Krauze', 'dog', 'German Shepherd', 2.9, 'Blue', 108.3, '1/9/2000', 'Indigo', '864 Valley Edge Parkway', 'architect sexy mindshare', 0, 'IMG_8981.jpg');
insert into pets (name, class, breed, age, color, weight, birthday, eye_color, location, bio, price, image_url) values ('Debee Alcock', 'cat', 'Russian Blue', 18.1, 'Violet', 10.5, '12/9/2011', 'Fuscia', '049 Summit Hill', 'synergize efficient e-business', 3040.50, 'IMG_8981.jpg');
insert into pets (name, class, breed, age, color, weight, birthday, eye_color, location, bio, price, image_url) values ('Neilla Harkness', 'dog', 'Golden Retriever', 19.4, 'Maroon', 124.6, '12/9/2017', 'Aquamarine', '12240 American Junction', 'disintermediate global channels', 1245.90, 'IMG_8981.jpg');
insert into pets (name, class, breed, age, color, weight, birthday, eye_color, location, bio, price, image_url) values ('Lilia Kench', 'dog', 'German Shepherd', 1.9, 'Orange', 143.9, '3/18/2017', 'Turquoise', '900 Prairie Rose Place', 'extend clicks-and-mortar systems', 1536.89, 'IMG_8981.jpg');
insert into pets (name, class, breed, age, color, weight, birthday, eye_color, location, bio, price, image_url) values('Eziechiele Harcase', 'bird', 'Budgerigar/Budgie', 2.5, 'Yellow', 0.04, '2018-03-15', 'Black', '123 Bird Lane', 'cheerful and social bird', 50.00, 'budgie1.jpg');
insert into pets (name, class, breed, age, color, weight, birthday, eye_color, location, bio, price, image_url) values('Rodge Joselin', 'bird', 'Cockatiel', 3.0, 'Gray', 0.08, '2019-06-20', 'Orange', '456 Feather Street', 'playful and affectionate', 80.00, 'cockatiel1.jpg');
insert into pets (name, class, breed, age, color, weight, birthday, eye_color, location, bio, price, image_url) values('Jim Flea', 'bird', 'Java Sparrow', 1.8, 'White', 0.03, '2021-09-10', 'Red', '789 Aviary Road', 'active and chirpy companion', 40.00, 'java_sparrow1.jpg');
insert into pets (name, class, breed, age, color, weight, birthday, eye_color, location, bio, price, image_url) values('Curtice Breawood', 'bird', 'Budgerigar/Budgie', 4.2, 'Green', 0.05, '2017-11-22', 'Blue', '321 Wing Circle', 'loves to mimic sounds', 60.00, 'budgie2.jpg');
insert into pets (name, class, breed, age, color, weight, birthday, eye_color, location, bio, price, image_url) values('Lorianne Paddefield', 'bird', 'Cockatiel', 2.7, 'Yellow', 0.09, '2020-01-30', 'Gray', '654 Nest Avenue', 'gentle and friendly nature', 75.00, 'cockatiel2.jpg');
insert into user_uploads (user_id, pet_id) values (1, 1);
insert into user_uploads (user_id, pet_id) values (2, 2);
insert into user_uploads (user_id, pet_id) values (3, 3);
insert into user_uploads (user_id, pet_id) values (4, 4);
insert into user_uploads (user_id, pet_id) values (5, 5);
insert into user_uploads (user_id, pet_id) values (6, 6);
insert into user_uploads (user_id, pet_id) values (7, 7);
insert into user_uploads (user_id, pet_id) values (8, 8);
insert into user_uploads (user_id, pet_id) values (9, 9);
insert into user_uploads (user_id, pet_id) values (10, 10);
insert into user_uploads (user_id, pet_id) values (11, 11);
insert into user_uploads (user_id, pet_id) values (12, 12);
insert into user_uploads (user_id, pet_id) values (13, 13);
insert into user_uploads (user_id, pet_id) values (14, 14);
insert into user_uploads (user_id, pet_id) values (15, 15);
insert into user_uploads (user_id, pet_id) values (16, 16);
insert into user_uploads (user_id, pet_id) values (17, 17);
insert into user_uploads (user_id, pet_id) values (18, 18);
insert into user_uploads (user_id, pet_id) values (19, 19);
insert into user_uploads (user_id, pet_id) values (20, 20);
insert into user_uploads (user_id, pet_id) values (21, 21);
insert into user_uploads (user_id, pet_id) values (22, 22);
insert into user_uploads (user_id, pet_id) values (23, 23);
insert into user_uploads (user_id, pet_id) values (24, 24);
insert into user_uploads (user_id, pet_id) values (25, 25);

insert into cart (user_id, pet_id) values (1, 3);
insert into cart (user_id, pet_id) values (1, 4);
insert into cart (user_id, pet_id) values (2, 10);
insert into cart (user_id, pet_id) values (5, 20);
insert into cart (user_id, pet_id) values (5, 11);
insert into cart (user_id, pet_id) values (6, 15);
insert into cart (user_id, pet_id) values (7, 5);
insert into cart (user_id, pet_id) values (8, 7);
insert into cart (user_id, pet_id) values (9, 9);
insert into cart (user_id, pet_id) values (10, 1);

insert into wishlist (user_id, pet_id) values (1, 3);
insert into wishlist (user_id, pet_id) values (1, 7);
insert into wishlist (user_id, pet_id) values (1, 5);
insert into wishlist (user_id, pet_id) values (2, 10);
insert into wishlist (user_id, pet_id) values (2, 9);
insert into wishlist (user_id, pet_id) values (5, 6);
insert into wishlist (user_id, pet_id) values (5, 7);
insert into wishlist (user_id, pet_id) values (8, 1);
insert into wishlist (user_id, pet_id) values (20, 10);
insert into wishlist (user_id, pet_id) values (20, 5);
